# Idea thanks to https://github.com/sw-yx/gh-action-data-scraping/

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'
    # Was originally every hour, now every five minutes, but won't be that often anyway: https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/
name: Generate Changelog
jobs:
  build:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Generate
      run: npm run generate
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you